# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efe1f9c5301e7c9b835d0cd9c3c69fb4c1213702984b08ecf38a42d6d57f027066669708a1fd0066f528955a32158f058f717159a9dd330981de085436942a78

test:
  secret_key_base: 9731c9d927c6dff9ef4ea29ff47396977e8dee0f1cd7463d7c2169c621a690f91b82a2a6d9e3db76ca5917f5f4477f4d99c2f2d759a7b979180502ed4ccd4e61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
